### PR TITLE
feat: add qml common component import by qrc examples

### PR DESCRIPTION
**Pull request by smallsunsun1**
1. add more complext qml example (you can use other predefined qml files)
2. add support for data and env attributes for qt_cc_binary

### CODE REVIEW

**Comment by Vertexwahn** [comment]
Thanks for your contribution again! 

BTW: macOS build is still broken (was working before your changes ;) - maybe you can investigate)

**Comment by smallsunsun1** [comment]
> Thanks for your contribution again!
> 
> BTW: macOS build is still broken (was working before your changes ;) - maybe you can investigate)

also check code before my commit，it seems only use uic and moc，but now rcc are needed and cause this problem in macos x86_64，maybe i can check it in next days when i get macos x86_64

**Comment by Vertexwahn** [comment]
@smallsunsun1 

I added another demo called `uic_demo` in the test directory.

In the Ubuntu CI run you can see this error:

```
ERROR: /home/runner/work/rules_qt6/rules_qt6/tests/uic_demo/BUILD.bazel:47:14: Action uic_demo/ui_mainwindow.h failed: (Exit 1): uic failed: error executing command external/qt_6.4.0_linux_desktop_gcc_64/libexec/uic uic_demo/mainwindow.ui -o bazel-out/k8-fastbuild/bin/uic_demo/ui_mainwindow.h
```

uic is in the external folder:
image

If I hardcode the absolute path e.g. `/home/vertexwahn/dev/rules_qt6/tests/bazel-tests/external/qt_6.4.0_linux_desktop_gcc_64/libexec/uic` everything works.

Any ideas how to fix this?

**Comment by smallsunsun1** [comment]
> @smallsunsun1
> 
> I added another demo called `uic_demo` in the test directory.
> 
> In the Ubuntu CI run you can see this error:
> 
> ```
> ERROR: /home/runner/work/rules_qt6/rules_qt6/tests/uic_demo/BUILD.bazel:47:14: Action uic_demo/ui_mainwindow.h failed: (Exit 1): uic failed: error executing command external/qt_6.4.0_linux_desktop_gcc_64/libexec/uic uic_demo/mainwindow.ui -o bazel-out/k8-fastbuild/bin/uic_demo/ui_mainwindow.h
> ```
> 
> uic is in the external folder: image
> 
> If I hardcode the absolute path e.g. `/home/vertexwahn/dev/rules_qt6/tests/bazel-tests/external/qt_6.4.0_linux_desktop_gcc_64/libexec/uic` everything works.
> 
> Any ideas how to fix this?

you can see qt.bzl, i add a tags = ["local"] in qt_resource impl, which call gencpp, and in gencpp, you need process tags= ["local"],
exec_requirements = {}
    for elem in ctx.attr.tags:
        exec_requirements[elem] = "1"

    ctx.actions.run(
        inputs = [resource for _, resource in resource_files] + [ctx.file.qrc],
        outputs = [ctx.outputs.cpp],
        arguments = args,
        executable = info.rcc_path,
        execution_requirements = exec_requirements,
    )
because in linux, bazel by default run on sandbox, which cause this problem. explicit mark rule run on local can fix this.

**Comment by Vertexwahn** [comment]
I added the change - no everything seems to work

**Pull request merged**
