### PR TITLE
feat: support linux, macos, windows and qml demo and test on all systems

### PR DESCRIPTION
**Pull request by smallsunsun1**
1. add qml support
2. rename repo name to rules_qt
3. use download qt-toolchain (rcc, uic, moc) rather than hardcode local path

### CODE REVIEW

**Comment by Vertexwahn** [comment]
Just have seen this PR (did not get any notification) - Currently, the CI jobs are all red - needs to be fixed before I can merge the PR

**Review by Vertexwahn — APPROVED** [review]

**Comment by Vertexwahn** [comment]
Thanks for your contribution! I merged it even CI is broken currently - happy to see QML support!

**Comment by smallsunsun1** [comment]
> Just have seen this PR (did not get any notification) - Currently, the CI jobs are all red - needs to be fixed before I can merge the PR

I checked the ci and my local environment, problem is ci use bazel build //..., but in my local mode, only build //:all and //qml_demo/...

**Comment by smallsunsun1** [comment]
when we use bazel build //..., bazel will try to build code in tools directory ,which will cause this problem, maybe we can change ci build targets or change macos to use http_archive rather than local mode, which will help on this problem

**Comment by smallsunsun1** [comment]
> support

ok, i will try open a new pr later to fix non english problem

**Pull request merged**
